project:
  type: website
  render:
    - "*.qmd"
    - "!publications/_template/"
    - "!people/_template/"


website:
  title: "LinkedEarth"
  site-url: "https://linkedearth.github.io/quarto_website/"
  repo-url: "https://github.com/LinkedEarth/quarto_website"
  favicon: images/linkedearth-logo.png
  twitter-card: true
  page-navigation: false
  search: true
  page-footer:
    background: "#f8f9fa"
    center: Â© 2025 LinkedEarth &middot; Made with
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
    right:
      - icon: github
        href: https://github.com/LinkedEarth/quarto_website

  navbar:
    search: true
    title: false
    logo: images/linkedearth-logo.png
    background: "#f8f9fa"
    logo-alt: "LinkedEarth"
    left:
      - href: index.qmd
        text: Home
      - href: data/index.qmd
        text: Data
      - href: tools/index.qmd
        text: Tools
      - href: community/index.qmd
        text: Community
      - href: training/index.qmd
        text: Training
      - href: funding/index.qmd
        text: Funding

  sidebar:
    - id: empty-to-suppress-sidebars-on-other-pages


format:
  html:
    theme: 
      - styles/custom.scss
      - yeti
    mainfont: Nunito Sans
    toc: true
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true
    resources:
      - images



